// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assignment_26.Contexts;

#nullable disable

namespace assignment_27.Migrations
{
    [DbContext(typeof(itiDbContext))]
    partial class itiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("assignment_27.Entitys.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Duration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("assignment_27.Entitys.Course_Inst", b =>
                {
                    b.Property<int>("Course_Id")
                        .HasColumnType("int");

                    b.Property<int>("Inst_Id")
                        .HasColumnType("int");

                    b.Property<double>("Evaluation")
                        .HasColumnType("float");

                    b.Property<int>("coursesId")
                        .HasColumnType("int");

                    b.Property<int>("instructorsId")
                        .HasColumnType("int");

                    b.HasKey("Course_Id", "Inst_Id");

                    b.HasIndex("coursesId");

                    b.HasIndex("instructorsId");

                    b.ToTable("Course_Insts");
                });

            modelBuilder.Entity("assignment_27.Entitys.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("assignment_27.Entitys.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Bounce")
                        .HasColumnType("float");

                    b.Property<double>("Hour_Rate")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<int>("departmentManyToOneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("departmentManyToOneId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("assignment_27.Entitys.Stud_Course", b =>
                {
                    b.Property<int>("Stud_Id")
                        .HasColumnType("int");

                    b.Property<string>("Course_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.HasKey("Stud_Id", "Course_Id");

                    b.HasIndex("StudentsId");

                    b.HasIndex("courseId");

                    b.ToTable("Stud_Courses");
                });

            modelBuilder.Entity("assignment_27.Entitys.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("departmentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("assignment_27.Entitys.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("assignment_27.Entitys.Course", b =>
                {
                    b.HasOne("assignment_27.Entitys.Topic", "Topic")
                        .WithMany("Courses")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("assignment_27.Entitys.Course_Inst", b =>
                {
                    b.HasOne("assignment_27.Entitys.Course", "courses")
                        .WithMany("course_Insts")
                        .HasForeignKey("coursesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("assignment_27.Entitys.Instructor", "instructors")
                        .WithMany("inst_course")
                        .HasForeignKey("instructorsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("courses");

                    b.Navigation("instructors");
                });

            modelBuilder.Entity("assignment_27.Entitys.Instructor", b =>
                {
                    b.HasOne("assignment_27.Entitys.Department", "departmentOneToOne")
                        .WithOne("instructorOneToOne")
                        .HasForeignKey("assignment_27.Entitys.Instructor", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("assignment_27.Entitys.Department", "departmentManyToOne")
                        .WithMany("instructorManyToOne")
                        .HasForeignKey("departmentManyToOneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("departmentManyToOne");

                    b.Navigation("departmentOneToOne");
                });

            modelBuilder.Entity("assignment_27.Entitys.Stud_Course", b =>
                {
                    b.HasOne("assignment_27.Entitys.Student", "Students")
                        .WithMany("Stud_Course")
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("assignment_27.Entitys.Course", "course")
                        .WithMany("course_stud")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Students");

                    b.Navigation("course");
                });

            modelBuilder.Entity("assignment_27.Entitys.Student", b =>
                {
                    b.HasOne("assignment_27.Entitys.Department", "department")
                        .WithMany("students")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("assignment_27.Entitys.Course", b =>
                {
                    b.Navigation("course_Insts");

                    b.Navigation("course_stud");
                });

            modelBuilder.Entity("assignment_27.Entitys.Department", b =>
                {
                    b.Navigation("instructorManyToOne");

                    b.Navigation("instructorOneToOne")
                        .IsRequired();

                    b.Navigation("students");
                });

            modelBuilder.Entity("assignment_27.Entitys.Instructor", b =>
                {
                    b.Navigation("inst_course");
                });

            modelBuilder.Entity("assignment_27.Entitys.Student", b =>
                {
                    b.Navigation("Stud_Course");
                });

            modelBuilder.Entity("assignment_27.Entitys.Topic", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
